<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy,-Scipy-and-Matplotlib" data-toc-modified-id="Numpy,-Scipy-and-Matplotlib-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy, Scipy and Matplotlib</a></span></li><li><span><a href="#NumPy" data-toc-modified-id="NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#Numpy-arrays" data-toc-modified-id="Numpy-arrays-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Numpy arrays</a></span><ul class="toc-item"><li><span><a href="#Memory-layout---Python-list-vs-numpy-ndarray" data-toc-modified-id="Memory-layout---Python-list-vs-numpy-ndarray-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Memory layout - Python list vs numpy ndarray</a></span></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Creating arrays</a></span></li></ul></li><li><span><a href="#Numpy-datatypes" data-toc-modified-id="Numpy-datatypes-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Numpy datatypes</a></span></li><li><span><a href="#Working-with-numpy-arrays" data-toc-modified-id="Working-with-numpy-arrays-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Working with numpy arrays</a></span><ul class="toc-item"><li><span><a href="#numpy-ufuncs" data-toc-modified-id="numpy-ufuncs-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>numpy ufuncs</a></span></li></ul></li><li><span><a href="#Array-indexing-and-slicing" data-toc-modified-id="Array-indexing-and-slicing-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Array indexing and slicing</a></span><ul class="toc-item"><li><span><a href="#Array-filtering" data-toc-modified-id="Array-filtering-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>Array filtering</a></span></li><li><span><a href="#Array-IO" data-toc-modified-id="Array-IO-2.4.2"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>Array IO</a></span></li><li><span><a href="#Basic-statistics" data-toc-modified-id="Basic-statistics-2.4.3"><span class="toc-item-num">2.4.3&nbsp;&nbsp;</span>Basic statistics</a></span></li></ul></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Linear Algebra</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Solving-system-of-equations" data-toc-modified-id="Solving-system-of-equations-2.5.0.1"><span class="toc-item-num">2.5.0.1&nbsp;&nbsp;</span>Solving system of equations</a></span></li></ul></li><li><span><a href="#numpy---many-more-features" data-toc-modified-id="numpy---many-more-features-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>numpy - many more features</a></span></li></ul></li></ul></li></ul></div>

# Numpy, Scipy and Matplotlib
There are numerous scientific programs, packages and libraries written in various programming languages: 

*Mathematica, Maple, Matlab, Root, R, Numerical Recipes, etc*

For python the de-facto standard are the 
*Numpy, Scipy and Matplotlib* packages.
They allow to combine the ease and flexibility of Python programming
with efficient and powerful libraries, which provide state-of-the art functionality and fast execution also for large applications. 



# NumPy

Applications in Science and Physics often require very cpu-intensive operations, e.g:

* large equation systems
* matrices 
* numerical integration
* fourier-transformation
* random number generation
* ...

Rich legacy of numerical libraries written e.g. in 
 Fortran or C/C++ (e.g. Numerical Recipes). 
This is also used with *numpy*, which offers an interface to BLAS (Basic Linear Algebra Library) and ATLAS (Automatically Tuned Linear Algebra Software).

Moreover, *numpy* offers a very efficient Array-Datatype `ndarray` which provides a homogenous store for numerical data types and operations and functions for it. The backend is written in **`C`** and allows efficient vectorised or parallelized operations on large array structures.


In [2]:
%%timeit
# std pythons lists
a = range(10000000)
b = range(10000000)
c = []
for i in range(len(a)):
  c.append(a[i] + b[i])


1 loop, best of 3: 4.17 s per loop


In [3]:
%%timeit
# same with numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000) 
c = a + b


10 loops, best of 3: 82.1 ms per loop


## Numpy arrays
The basis of numpy is the **`ndarray`**, this is a homogenous array especially for numerical data types.
* It supports many different kinds of integer, float and boolean data types
* but homogenous, all elements in array of same type
  * *(not quite true, elements can also be Python objects and thereby any Python type, but that's exceptional case)*
* not just a list, it contains additional information on *shape* 
* many utility functions to reate, fill, store, extract, manipulate


In [11]:
# std python list very flexible
L = list(range(10)) # homogenous list
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
# but also arbitrary elements
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [13]:
# numpy array from python list
np.array([1, 4, 2, 5, 3]) #  integer elements --> integer array

array([1, 4, 2, 5, 3])

In [14]:
# numpy array from python list
np.array([1, 4.2, 2, 5, 3]) #  one float --> float array

array([ 1. ,  4.2,  2. ,  5. ,  3. ])

In [17]:
# can also enforce data type
np.array([1, 4, 2, 5, 3],dtype='float32')

array([ 1.,  4.,  2.,  5.,  3.], dtype=float32)

### Memory layout - Python list vs numpy ndarray

* A python list is actually only a list of **pointers/references** to the  actula objects
  * very flexible, but also inefficient when accessing large arrays
* in contrast, numpy ndarray contains directly all elements
  * efficient to process but needs to have specific data type
    


![Array Memory Layout](figures/array_vs_list.png)

### Creating arrays

In [18]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [27]:
# Create an array of 10 values logarithmically spaced between 10**0 and 10**5
np.logspace(0,5,10)

array([  1.00000000e+00,   3.59381366e+00,   1.29154967e+01,
         4.64158883e+01,   1.66810054e+02,   5.99484250e+02,
         2.15443469e+03,   7.74263683e+03,   2.78255940e+04,
         1.00000000e+05])

In [28]:
# Create an array of 5 uniformly distributed
# random values between 0 and 1
np.random.random(5)

array([ 0.6265192 ,  0.45668818,  0.86940203,  0.35060164,  0.93258932])

In [29]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[ 0.40870482,  0.43140663,  0.8316238 ],
       [ 0.5655511 ,  0.98869605,  0.50636745],
       [ 0.81968604,  0.21121699,  0.16256727]])

In [35]:
# Create an array of 10 normal distributed
# random values with mean 0 and std deviation 1
np.random.normal(0,1,10)

array([ 0.58750019,  0.11248179,  0.63549725,  0.50253517, -0.57231355,
        0.49357643,  0.41198692, -0.15094843,  0.52364019,  0.66422702])

## Numpy datatypes
In most cases Python/numpy automatically identifies suitable data-type, though sometimes it can be useful to explicitly specify the desired type.

Here the list of supported types:


| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

In [36]:
a=np.random.normal(0,1,10)
a.dtype   # data type available as field in ndarray

dtype('float64')

## Working with numpy arrays


In [37]:
a=np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]]) 
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 12]]


In [ ]:
# many fields and functions in ndarray
[m for m in dir(a) if not m.startswith('__')]

In [39]:
a.shape # layout stored in shape

(3, 4)

In [42]:
b=a.reshape(2,6) # can be changed

In [44]:
print(a.shape) # original unchanged
print(b.shape) 

(3, 4)
(2, 6)


In [45]:
a.T # transpose

array([[ 1,  4,  9],
       [ 2,  5, 10],
       [ 3,  6, 11],
       [ 4,  7, 12]])

In [46]:
-1*a # multiply with scalar

array([[ -1,  -2,  -3,  -4],
       [ -4,  -5,  -6,  -7],
       [ -9, -10, -11, -12]])

In [48]:
a+2.1 # add scalar

array([[  3.1,   4.1,   5.1,   6.1],
       [  6.1,   7.1,   8.1,   9.1],
       [ 11.1,  12.1,  13.1,  14.1]])

In [50]:
a+a # adding arrays element-by-element

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [18, 20, 22, 24]])

In [ ]:
a+b # error - requires same shape

In [52]:
a*a # multiplying array element-by-element

array([[  1,   4,   9,  16],
       [ 16,  25,  36,  49],
       [ 81, 100, 121, 144]])

In [ ]:
a.dot(a) # matrix multiplication -- error aligned shapes required

In [54]:
a.dot(a.reshape(4,3)) # matrix multiplication: 3x4 times 4x3 works ok

array([[ 67,  75,  88],
       [130, 147, 175],
       [235, 267, 320]])

In [67]:
c=np.arange(4,8)
print(c, c.shape)

[4 5 6 7] (4,)


In [65]:
a.dot(c) # 3x4 matrix times 4-vec ok

array([ 60, 126, 236])

### numpy ufuncs


In [69]:
np.sqrt(a) # can apply std maths functions

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162]])

In [70]:
a**0.5 # and operators

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162]])

In [71]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

See here for detailed list of Numpy functions: 
http://wiki.scipy.org/Numpy_Example_List

## Array indexing and slicing
As for Python lists there are many sophisticated ways how to access or extract elements or sub-arrays

In [72]:
a=np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [73]:
a[1,2] # 2nd line, 3rd colun (index starts at 0)

6

In [74]:
a[1] # 2nd line

array([4, 5, 6, 7])

In [75]:
a[-1] #  last line

array([ 9, 10, 11, 12])

In [76]:
a[:2] # 1st and 2nd line

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [78]:
a[:,2] # 3rd column

array([ 3,  6, 11])

In [79]:
a[:2,1:3] # ...

array([[2, 3],
       [5, 6]])

### Array filtering

In [80]:
a=np.array(range(100))

In [81]:
np.where(a>50)

(array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [82]:
a>80 # returns boolean array if elements fullfill criteria

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [83]:
a[a>80] # sub-array fullfilling criteria

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

### Array IO

In [88]:
data = np.loadtxt('numbers.dat') # reads numbers from text file and stores in numpy array
data.shape

(100,)

In [91]:
a=np.array(np.arange(1,10).reshape(3,3))
print('a=',a)

a.tofile('a.data')
b=np.fromfile('a.data', dtype=int) # watch out, shape info lost
print('b=',b)


a= [[1 2 3]
 [4 5 6]
 [7 8 9]]
b= [1 2 3 4 5 6 7 8 9]


### Basic statistics


In [94]:
T=np.array([1.3,4.5,2.8,3.9])
print (T.mean(), T.std(), T.var()) # Mean, std deviation, Variance

3.125 1.21732288239 1.481875


In [97]:
T=np.random.normal(10.,2.,1000) # 1000 normal distributed random numbers, mean 10, std 2
print (T.mean(), T.std(), T.var())

9.8400479504 2.15189813123 4.63066556721


In [98]:
# correlation
T=np.array([1.3,4.5,2.8,3.9])
P=np.array([2.7,8.7,4.7,8.2])
print (np.corrcoef([T,P]))

[[ 1.          0.98062258]
 [ 0.98062258  1.        ]]


## Linear Algebra

In [99]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [100]:
a.diagonal() # Diagonalwerte

array([ 0,  5, 10])

In [102]:
# standard matrices
print(np.ones(3))
print(np.zeros(3))
print(np.eye(3))

[ 1.  1.  1.]
[ 0.  0.  0.]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### Solving system of equations

In [103]:
from numpy.linalg import inv
a=np.array([[3,1,5],[1,0,8],[2,1,4]])
inva=inv(a) # matrix inversion
print(a)
print(inva)
np.dot(a,inva) # should give unity matrix

[[3 1 5]
 [1 0 8]
 [2 1 4]]
[[ 1.14285714 -0.14285714 -1.14285714]
 [-1.71428571 -0.28571429  2.71428571]
 [-0.14285714  0.14285714  0.14285714]]


array([[  1.00000000e+00,   5.55111512e-17,   2.77555756e-16],
       [ -2.22044605e-16,   1.00000000e+00,   2.22044605e-16],
       [ -2.22044605e-16,   0.00000000e+00,   1.00000000e+00]])

In [104]:
from numpy.linalg import solve
print(a)
b=np.array([6,7,8])
x=solve(a,b) # solve equation a*x = b
print(x)
np.dot(a,x) # test: should give b


[[3 1 5]
 [1 0 8]
 [2 1 4]]
[-3.28571429  9.42857143  1.28571429]


array([ 6.,  7.,  8.])

### numpy - many more features
* advanced Linalg tools 
* numerical methods, ...